
ALTER TABLE public.personal_property_records
  ADD COLUMN IF NOT EXISTS firearm_type text,
  ADD COLUMN IF NOT EXISTS firearm_make text,
  ADD COLUMN IF NOT EXISTS firearm_model text,
  ADD COLUMN IF NOT EXISTS firearm_caliber text,
  ADD COLUMN IF NOT EXISTS firearm_serial_masked text,
  ADD COLUMN IF NOT EXISTS firearm_serial_encrypted text,
  ADD COLUMN IF NOT EXISTS firearm_finish text,
  ADD COLUMN IF NOT EXISTS firearm_barrel_length text,
  ADD COLUMN IF NOT EXISTS firearm_action_type text,
  ADD COLUMN IF NOT EXISTS firearm_year_manufactured integer,
  ADD COLUMN IF NOT EXISTS firearm_country_origin text,
  ADD COLUMN IF NOT EXISTS firearm_storage_location text,
  ADD COLUMN IF NOT EXISTS firearm_safe_code_masked text,
  ADD COLUMN IF NOT EXISTS firearm_safe_code_encrypted text,
  ADD COLUMN IF NOT EXISTS firearm_who_has_access text,
  ADD COLUMN IF NOT EXISTS firearm_is_loaded boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS firearm_ammunition_location text,
  ADD COLUMN IF NOT EXISTS firearm_purchase_date date,
  ADD COLUMN IF NOT EXISTS firearm_ffl_dealer text,
  ADD COLUMN IF NOT EXISTS firearm_purchased_from_type text,
  ADD COLUMN IF NOT EXISTS firearm_is_registered boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS firearm_registration_state text,
  ADD COLUMN IF NOT EXISTS firearm_transfer_restrictions text,
  ADD COLUMN IF NOT EXISTS firearm_ccw_permit boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS firearm_ccw_state text,
  ADD COLUMN IF NOT EXISTS firearm_ccw_expiration date,
  ADD COLUMN IF NOT EXISTS firearm_disposition_action text,
  ADD COLUMN IF NOT EXISTS firearm_disposition_recipient text,
  ADD COLUMN IF NOT EXISTS firearm_attorney_to_contact text,
  ADD COLUMN IF NOT EXISTS firearm_special_instructions text;
